# Preprocessing steps
# 1) First you need to run the C2Vsim model and generate the hdf outputs
# 2) Run the following line after you have set the correct paths and variables in the first section of the script
source("PreprocTrack.R")
# then you can and you should clear the workspace.
# The prepocessing step hace to be run only once


# Examples

# Prepare the data. 
# This is needed for each R session

# set the path where the Rwrkspc is
setwd("f:/UCDAVIS/IWFM_track/Rwrkspc")
# Enable the functions
source("iwfm_funct.R")
# Generate a list of time steps
simTime <- iwfm.SimTime()
# load the data. This will load the data that have been generated by the Preprocessing step
D <- iwfm.loadData("PartTrackData.h5")

# Average the velocity field
# You can use the transient field, however 30 years is not enough time for a particle to exit the domain
# The following is going to average the velocity field for 10 years
D <- iwfm.AverageVelField(ISOdate(2005,10,31), ISOdate(2015,9,30), D, simTime)


# Read well info
wells <- read.table(file = "welldata.dat", header = TRUE)

# for each well generate a number of particles around it
# The following line will generate 40 particles per well, evenlly distributed around the screen length 
# at a distance of 5 meters arounf the well coordinates
particles <- iwfm.wellParticles(wells, 20, 10, D$MSH, D$XY, D$STRAT, D$BC)

# Create an option variable
po <- iwfm.options()

# Run particle tracking
strm <- iwfm.traceParticles(particles, D, po)

# isolate the exit points for a particular well e.g. 2
SourceArea <- iwfm.sourceOutline(2, strm)

